[general]
output = "results"
num_threads = 10
max_concurrent_downloads = 8
apikey = ""

[window]
mod = "win_nts"
wn = 20000
height_factor = 20
ngenes = 10
minwin = 2000
minwin_type = "both"

[tree]
tree_mode = "fast_ml"
tree_file = "target_prots.nwk"
nj_algorithm = "nj"

[aai]
aai_mode = "wgrr"
aai-subset-mode = "target_region"

[ani]
ani_mode = "fastani"

[clustering]
cand_mode = "best_id"
clust_method = "diamond_deepclust"

[annotations]
padloc = false
deffinder = false
ncrna = false
cctyper = false
domains = ""
domains_metadata = ""
min_prevalence = 0.0
genomad = false
antidefense = false
phrogs = false
sorfs = false
prot_links = false
nt_links = false
nt_aln_mode = "blastn"

[paths]
assembly_folder = ""
assembly_db = "/env/db/hoodini"
img_db = ""
img_nuc = ""
blast = ""
img = "/mnt/fastdb/imgpr_imgvr/data_structure/"
img_metadata = "/mnt/fastdb/imgpr_imgvr/merged_metadata/imgvr_pr_taxids.txt"
keep = false
force = false
